name: Build and Store WAR File

on:
  push:
    branches:
      - prod # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build WAR
        run: ./mvnw clean package -DskipTests=true

      - name: Upload WAR
        uses: actions/upload-artifact@v2
        with:
          name: my-application-war
          path: target/*.war
